name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Fetch iris
      uses: actions/checkout@v2
      with:
        repository: 'IrisShaders/Iris'
        ref: 'sodium-compatibility'
        path: 'iris'
    - name: Iris publishToMavenLocal
      run: cd ./iris && ./gradlew publishToMavenLocal && cd ..
    - name: Build artifacts
      run: ./gradlew build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: build/libs
